# Generated by Django 3.1.4 on 2021-01-04 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('master', models.CharField(max_length=50)),
                ('introduce', models.TextField()),
                ('inviting', models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule_year', models.CharField(max_length=4)),
                ('schedule_month', models.CharField(max_length=2)),
                ('schedule_date', models.CharField(max_length=2)),
                ('schedule_hour', models.CharField(max_length=2)),
                ('schedule_min', models.CharField(max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_todo', to='group.group')),
            ],
        ),
    ]
