# Generated by Django 3.1.4 on 2021-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptodo',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
