# Generated by Django 3.1.4 on 2021-01-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_grouptodo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptodo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_todo', to='accounts.user'),
            preserve_default=False,
        ),
    ]
