# Generated by Django 3.1.4 on 2021-01-03 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('master', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
