# Generated by Django 3.1.4 on 2021-01-03 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inviting',
            field=models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
