# Generated by Django 3.1.4 on 2021-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        ('accounts', '0005_auto_20210104_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='host',
        ),
        migrations.AddField(
            model_name='group',
            name='todo',
            field=models.ManyToManyField(related_name='group_Todo', to='todos.Todo'),
        ),
    ]
