# Generated by Django 3.1.4 on 2021-01-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_delete_grouptodo'),
        ('accounts', '0007_auto_20210104_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
