# Generated by Django 3.1.4 on 2020-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
