# Generated by Django 3.1.4 on 2021-01-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210104_1929'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('schedule_year', models.CharField(max_length=4)),
                ('schedule_month', models.CharField(max_length=2)),
                ('schedule_date', models.CharField(max_length=2)),
                ('schedule_hour', models.CharField(max_length=2)),
                ('schedule_min', models.CharField(max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_todo', to='accounts.group')),
            ],
        ),
    ]
